apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
data:
  GMAIL_OAUTH_CLIENT_SECRET: R09DU1BYLVRldnJvcUpmcmtPdWs4SEdNZ2h6Wjh3Qk9ZUWE=
  UPLOAD_CARE_SECRT_KEY: OWM2ZjQ3MTgzYjNkNWZhNTRhZjE=
  JWT_SECRET: c2ZrbHNka2ZsbXNramZrbHNmamtsc2Zqc2RmbGtzbWRmZHNvZmtkc2xta2Zqaw==
